Integer totalOfSum = 0;
List<Integer> numsOfList = new List<Integer>();
for(Integer i = 1; i <= 20; i++){
    numsOfList.add(i);    
}
System.debug('List Of Number: ' + numsOfList);
for(Integer i = 1; i < numsOfList.size(); i++){
    if(Math.mod(numsOfList[i], 2) == 0){
        totalOfSum = totalOfSum + numsOfList[i];
    	System.debug('totalSum Value: ' + totalOfSum);
    }
	
}

System.debug('Final Sumation: '+ totalOfSum);